### ISSUE TITLE
Injection results for ds != 1 cannot be saved

### ISSUE THREAD

**Issue by HarrisonS-Phys** [maxisi/ringdown#41] opened 2024-06-04 15:00 UTC
When loading a config file using ringdown.Fit.from_config(), and then running the fit, if ds != 1 then the result object is not properly saved and the run crashes. This happens after the sampling itself has completed.

**Comment by maxisi** [comment] 2024-06-04 19:11
Please provide the full traceback (and ideally minimum working code to reproduce the error)

**Comment by maxisi** [comment] 2024-10-31 00:38
I cannot reproduce this so I'm closing this issue, please reopen as needed

**Closed by maxisi** 2024-10-31 00:38 UTC
Labels: bug, invalid
